#!/usr/bin/env python
'''
call the script:
    python create_hashes.py 100
to generate 100 individual hashes per line
 
Recommended usage would be:
    python create_hashes.py 100 > hashes.txt
for UUCSS
'''
import argparse
import uuid

parser = argparse.ArgumentParser(description='''
`python create_hashes.py 100` would generate 100 individual hashes per line
`python create_hashes.py 100 > hashes.txt` to write to a file''')
parser.add_argument('number', type=int,
                    help="Integer number of hashes to generate.")

def unique_id():
    print uuid.uuid4().hex[:5]

def do_it_alot(num_times):
    for _ in range(num_times):
        unique_id()

if __name__ == '__main__':
    args = parser.parse_args()
    do_it_alot(args.number)
